### ISSUE TITLE
qfortecon Spring 2021

### ISSUE THREAD

**Issue by fevangelista** [evangelistalab/qforte#79]
# TODOs
- [ ] Class renaming

**Comment by JonathonMisiewicz** [comment]
Wait, what's a "fermionic quantum computer"?

**Comment by JonathonMisiewicz** [comment]
For the sake of coordination, my personal QForte to-do list is:

- [ ] Wait for currently running QForte computation to complete
- [ ] Submit PR in progress to remove code duplication between VQE and PQE.
- [ ] Finish class renaming, #57 

After that, I'm not sure what my next QForte project will be. If you are going to take an issue, _please_ say so, so no effort gets duplicated.

**Comment by fevangelista** [comment]
Is someone working on "Can we pass a list of gates to the QuantumCircuit constructor, to bypass add_gate?" or is this already a working feature?

**Comment by nstair** [comment]
> Is someone working on "Can we pass a list of gates to the QuantumCircuit constructor, to bypass add_gate?" or is this already a working feature?

It is already a working feature, but uses a function rather than an overload of the constructor. Nan added it some time ago. Syntax looks like qforte.build_circuit('X_1 Y_2 X_3 Y_4').

**Comment by fevangelista** [comment]
It would still be useful to support the following:
```
g1 = qforte.gate(...)
g2 = qforte.gate(...)
circ.add([g1,g2]) # or circ.add(g1,g2)
```
